---
- name: Docker | Instalar y configurar Docker Engine
  tags: docker
  become: true
  block:
    - name: Docker | Instalar paquetes de prerrequisitos
      ansible.builtin.apt:
        name: "{{ developer_docker_prerequisites }}"
        state: present
        update_cache: true

    - name: Docker | Asegurar que el directorio de keyrings de APT existe
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Docker | Añadir la clave GPG oficial de Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /tmp/docker.gpg
        mode: '0644'

    - name: Docker | Convertir la clave GPG al formato requerido
      ansible.builtin.shell: >
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg
      changed_when: false

    - name: Docker | Limpiar archivo temporal de clave GPG
      ansible.builtin.file:
        path: /tmp/docker.gpg
        state: absent

    - name: Docker | Añadir el repositorio de Docker
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/{{ ansible_distribution | lower }}
          {{ ansible_distribution_release }} stable
        state: present
        filename: docker
        update_cache: true

    - name: Docker | Instalar Docker Engine y plugins
      ansible.builtin.apt:
        name: "{{ developer_docker_packages }}"
        state: present

    - name: Docker | Asegurar que el servicio Docker esté activo y habilitado
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Docker | Asegurar que el grupo 'docker' existe
      ansible.builtin.group:
        name: docker
        state: present

    - name: Docker | Añadir el usuario al grupo 'docker' para evitar usar sudo
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        groups: docker
        append: true
