---
- name: Kubectl | Instalar y configurar kubectl desde el nuevo repositorio de pkgs.k8s.io
  tags: kubectl
  become: true
  block:
    - name: Kubectl | Instalar paquetes de prerrequisitos
      ansible.builtin.apt:
        name: "{{ developer_kubectl_prerequisites }}"
        state: present
        update_cache: true

    - name: Kubectl | Eliminar el repositorio antiguo y obsoleto (apt.kubernetes.io)
      ansible.builtin.apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: absent
        filename: kubernetes

    - name: Kubectl | Añadir la nueva clave GPG de Kubernetes
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /tmp/kubernetes-release.key
        mode: '0644'

    - name: Kubectl | Convertir y guardar la clave GPG
      ansible.builtin.shell: >
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      changed_when: false

    - name: Kubectl | Añadir el nuevo repositorio de Kubernetes (pkgs.k8s.io)
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
        state: present
        filename: kubernetes-pkgs
        update_cache: true

    - name: Kubectl | Instalar kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
