---
- name: Include vars
  ansible.builtin.include_vars: "{{ role_path }}/vars.yml"
  tags: always
  no_log: true

- name: Include
  block:
    - name: Developer - Packages
      ansible.builtin.import_tasks: packages_dev.yml
    - name: Developer - Docker
      ansible.builtin.import_tasks: docker.yml
    - name: Developer - Meld
      ansible.builtin.import_tasks: meld.yml
    - name: Developer - Code
      ansible.builtin.import_tasks: code.yml
    - name: Developer - Python
      ansible.builtin.import_tasks: python.yml
    - name: Developer - Git
      ansible.builtin.import_tasks: git.yml
    - name: Developer - Fixes
      ansible.builtin.import_tasks: fixes.yml
    - name: Developer - Prepare RemoteDev
      ansible.builtin.import_tasks: prepare_remote_dev.yml
    - name: Developer - Ssh
      ansible.builtin.import_tasks: ssh.yml
    - name: Developer - GH
      ansible.builtin.import_tasks: gh_cli.yml
