---
- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Restart GDM
  ansible.builtin.systemd:
    name: gdm3
    state: restarted

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  failed_when: false
  # En contenedores Docker y algunas configuraciones, systemd-resolved puede no existir

- name: Restart UFW
  ansible.builtin.systemd:
    name: ufw
    state: restarted
  failed_when: false

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  failed_when: false
