---
# Usuario genérico para ejecutar algunas tareas
remote_regular_user: "{{ ansible_env.SUDO_USER }}"
remote_regular_user_uid: "{{ ansible_user_uid }}"

# Extensiones predefinidas para sysadmin
vscode_extension_list_sysadmin:
  # Container Tools
  - ms-azuretools.vscode-containers
  # Dev Containers
  - ms-vscode-remote.remote-containers
  # Docker
  - ms-azuretools.vscode-docker
  # Docker DX
  - docker.docker
  # GitHub Copilot
  - github.copilot
  # GitHub Copilot Chat
  - github.copilot-chat
  # GitLens
  - eamodio.gitlens
  # Kubernetes
  - ms-kubernetes-tools.vscode-kubernetes-tools
  # Pylance
  - ms-python.vscode-pylance
  # Python
  - ms-python.python
  # Python Debugger
  - ms-python.debugpy
  # Python Environments
  - ms-python.vscode-python-envs
  # YAML
  - redhat.vscode-yaml
  # knative
  - redhat.vscode-knative

# --- Configuración para KVM/QEMU ---
# Paquetes principales para KVM y herramientas de virtualización
sysadmin_kvm_packages:
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - bridge-utils
  - virt-manager
  - virtinst
  - virt-viewer

# Grupos a los que añadir el usuario para usar KVM
sysadmin_kvm_user_groups:
  - libvirt
  - kvm

# --- Configuración para NordVPN ---
sysadmin_nordvpn_gpg_path: "/usr/share/keyrings/nordvpn-archive-keyring.gpg"
sysadmin_nordvpn_repo_line: "deb [signed-by={{ sysadmin_nordvpn_gpg_path }}] https://repo.nordvpn.com/deb/nordvpn/debian stable main"
sysadmin_nordvpn_package: "nordvpn"

# --- Configuración del Tema de Iconos Numix ---
sysadmin_icon_packages:
  - numix-icon-theme-circle
  - gnome-tweaks

sysadmin_numix_icon_theme_name: "Numix-Circle"
